import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const ResearchEthics = () => (
  <div className="min-h-screen bg-background">
    <div className="max-w-4xl mx-auto px-6 py-16">
      <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
        <ArrowLeft className="h-4 w-4" /> Back to home
      </Link>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="font-heading text-4xl font-bold mb-2">Research Ethics Guidelines</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 14, 2026</p>

        <div className="prose prose-invert prose-lg max-w-none space-y-8 text-foreground/90">
          <section><h2 className="font-heading text-2xl font-semibold text-foreground">Responsible Scientific Exploration</h2><p>ApeironAI empowers researchers to explore scientific frontiers responsibly. We expect all users to uphold the highest standards of scientific ethics, including honesty, objectivity, integrity, and openness in their research endeavors.</p></section>

          <section><h2 className="font-heading text-2xl font-semibold text-foreground">Hypothesis Generation Standards</h2><p>AI-generated hypotheses should be treated as research suggestions requiring human evaluation. Researchers must assess the plausibility, novelty, and testability of each hypothesis before pursuing experimental validation. Confidence scores provided by the AI are probabilistic estimates and should not be interpreted as definitive measures.</p></section>

          <section><h2 className="font-heading text-2xl font-semibold text-foreground">Data Integrity</h2><p>Users must not manipulate, fabricate, or falsify research data uploaded to or generated by ApeironAI. All research inputs should be based on legitimate data sources and properly cited.</p></section>

          <section><h2 className="font-heading text-2xl font-semibold text-foreground">Collaborative Research</h2><p>When using ApeironAI for collaborative research, all team members should be informed of AI tool usage. Proper credit and attribution should be given to all contributors, including disclosure of AI-assisted components.</p></section>

          <section><h2 className="font-heading text-2xl font-semibold text-foreground">Compliance</h2><p>Users must comply with all applicable institutional review board (IRB) requirements, research ethics regulations, and professional codes of conduct relevant to their field of study.</p></section>
        </div>
      </motion.div>
    </div>
  </div>
);

export default ResearchEthics;
